#!/usr/bin/env bash
# PhotoMemory Dev Loop — Ralph-style continuous Claude Code loop
# Each iteration: read plan → pick next task → execute → commit → update plan → repeat

set -euo pipefail

PROJECT_DIR="$HOME/.openclaw/workspace-daddy/projects/photomemory"
PLAN_FILE="$PROJECT_DIR/docs/CONTINUOUS_DEV_PLAN.md"
LOG_FILE="/tmp/photomemory-dev-loop.log"
MAX_ITERATIONS=20
ITERATION=0

log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

notify() {
  # Send notification via OpenClaw system event
  openclaw system event --text "$1" --mode now 2>/dev/null || true
}

log "🚀 PhotoMemory Dev Loop started (max $MAX_ITERATIONS iterations)"
notify "🚀 PhotoMemory Dev Loop 启动，开始全自动持续开发"

while [ $ITERATION -lt $MAX_ITERATIONS ]; do
  ITERATION=$((ITERATION + 1))
  log "━━━ Iteration $ITERATION/$MAX_ITERATIONS ━━━"

  # Find next unchecked task
  NEXT_TASK=$(grep -n '^\- \[ \]' "$PLAN_FILE" | head -1 || true)

  if [ -z "$NEXT_TASK" ]; then
    log "🎉 All tasks completed!"
    notify "🎉 PhotoMemory Dev Loop 全部任务完成！共执行 $ITERATION 次迭代"
    break
  fi

  LINE_NUM=$(echo "$NEXT_TASK" | cut -d: -f1)
  TASK_DESC=$(echo "$NEXT_TASK" | cut -d: -f2- | sed 's/^- \[ \] //')
  log "📋 Task: $TASK_DESC"

  # Determine which Sprint section this task belongs to
  SPRINT_SECTION=$(head -n "$LINE_NUM" "$PLAN_FILE" | grep -o 'Sprint [0-9]*:.*' | tail -1 || echo "Unknown Sprint")

  # Build the prompt for Claude Code
  PROMPT="你是 PhotoMemory 项目的开发者。当前任务：

## 上下文
- 项目路径：$PROJECT_DIR
- 当前 Sprint：$SPRINT_SECTION
- 任务：$TASK_DESC

## 要求
1. 仔细分析当前代码（读取相关文件）
2. 实现上述任务
3. 确保改动不会破坏现有功能
4. 完成后用 python3 验证关键模块能正确 import（比如 python3 -c 'import backend.api_server' 或类似检查）

## 约束
- 只做这一个任务，不要扩展范围
- 保持向后兼容
- 写清晰的代码注释
- 如果任务太大，只做最核心的部分

开始执行。"

  log "🔧 Running Claude Code..."
  cd "$PROJECT_DIR"

  # Run Claude Code (capture output, allow failure)
  CLAUDE_OUTPUT=$(claude --permission-mode bypassPermissions --print "$PROMPT" 2>&1) || {
    CLAUDE_EXIT=$?
    log "⚠️ Claude Code exited with code $CLAUDE_EXIT"
    # If context too large, try with shorter prompt
    if echo "$CLAUDE_OUTPUT" | grep -q "context length\|token"; then
      log "📏 Context too large, trying shorter prompt..."
      SHORT_PROMPT="在 $PROJECT_DIR 中执行：$TASK_DESC。只做这一个任务，保持向后兼容。"
      CLAUDE_OUTPUT=$(claude --permission-mode bypassPermissions --print "$SHORT_PROMPT" 2>&1) || {
        log "❌ Claude Code failed again, skipping task"
        notify "⚠️ Dev Loop 第 $ITERATION 次迭代失败：$TASK_DESC — Claude Code 上下文溢出"
        sleep 5
        continue
      }
    else
      log "❌ Claude Code failed, pausing loop"
      notify "❌ Dev Loop 暂停：$TASK_DESC 执行失败\n$CLAUDE_OUTPUT"
      break
    fi
  }

  log "✅ Claude Code finished"

  # Check if there are any changes to commit
  cd "$PROJECT_DIR"
  if git diff --quiet && git diff --cached --quiet; then
    log "⚠️ No changes detected, marking task as done anyway"
  else
    # Stage and commit
    git add -A
    COMMIT_MSG="feat: $TASK_DESC

Auto-generated by PhotoMemory Dev Loop (iteration $ITERATION)
Co-Authored-By: Claude Code <noreply@anthropic.com>"
    git commit -m "$COMMIT_MSG" || log "⚠️ git commit failed"
    log "📝 Committed: $TASK_DESC"
  fi

  # Update plan file - mark task as done
  TIMESTAMP=$(date '+%Y-%m-%d %H:%M')
  sed -i '' "${LINE_NUM}s/- \[ \]/- [x]/" "$PLAN_FILE"
  sed -i '' "${LINE_NUM}s/$/ ✅ ($TIMESTAMP)/" "$PLAN_FILE"

  # Commit the plan update
  git add "$PLAN_FILE"
  git commit -m "docs: mark task done - $TASK_DESC" || true

  notify "📦 PhotoMemory Dev Loop #$ITERATION
✅ 完成：$TASK_DESC
⏭️ 继续下一个任务..."

  log "⏳ Cooling down 10s before next iteration..."
  sleep 10
done

if [ $ITERATION -ge $MAX_ITERATIONS ]; then
  log "⏸️ Reached max iterations ($MAX_ITERATIONS), stopping"
  notify "⏸️ Dev Loop 达到最大迭代次数 ($MAX_ITERATIONS)，已暂停。可重新启动继续。"
fi

log "🏁 Dev Loop ended after $ITERATION iterations"
